# -*- coding: utf-8 -*-
"""40k

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fy0xtCytyoaIc79aaVUe0_8LdMD-qEHC
"""
import streamlit as st 
from rapidfuzz import fuzz

#---
st.title("⚔️ Warhammer 40K Codex Explorer")

st.markdown(
    """
    <style>

    @import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@400;600;800&display=swap');

    /* FONT (avoid breaking icons) */
    body, .stApp, h1, h2, h3, p, label, div {
        font-family: 'Cinzel', serif !important;
    }

    /* BACKGROUND */
    .stApp {
        background-color: #0b0b10;
        color: #e6e6e6;
    }

    section[data-testid="stSidebar"] label {
        color: #d0d0d0 !important;
        font-weight: 500;
    }

    /* TITLES */
    h1, h2, h3 {
        color: #d4af37;
        letter-spacing: 1px;
    }

    /* SEARCH LABEL */
    div[data-testid="stTextInput"] label {
        color: #d0d0d0 !important;
        font-weight: 500;
    }

    /* SEARCH INPUT */
    div[data-testid="stTextInput"] input {
        background-color: #f2f2f2 !important;
        color: #333 !important;
        border: 1px solid #555 !important;
        border-radius: 6px;
        padding: 8px;
        font-weight: 500;
    }	
    /* SEARCH TEXTBOX */
    div[data-testid="stTextInput"] input,
    div[data-testid="stTextInput"] input:focus,
    div[data-testid="stTextInput"] input:active {font-family: 'Cinzel', serif !important;
        background-color: #1a1a22 !important;
        color: #e6e6e6 !important;
        border: 1px solid #555 !important;
        box-shadow: none !important;
    }

    div[data-testid="stTextInput"] input::placeholder {
        color: #777 !important;
    }

    /* BUTTONS */
div.stButton > button {
    font-family: 'Cinzel', serif !important;
    background-color: #1a1a22;
    color: #d4af37;
    border: 1px solid #333;
    font-weight: 600;
    border-radius: 6px;
    transition: all 0.2s ease;
}

div.stButton > button:hover {
    background-color: #2a2a35;
    border: 1px solid #d4af37;
    color: #e6e6e6 ;
    transform: scale(1.02);
}

div.stButton > button:active {
    transform: scale(0.98);
    border: 1px solid #d4af37;
}
    /* EXPANDER (FIXED CLEAN VERSION) */
    div[data-testid="stExpander"] summary {
        display: flex !important;
        align-items: center !important;
        gap: 8px;
        white-space: nowrap;
        font-weight: 600;
        color: #e6e6e6 !important;
    }

    div[data-testid="stExpander"] summary svg {
        flex-shrink: 0;
    }

    div[data-testid="stExpander"] summary p {
        margin: 0 !important;
        overflow: hidden;
        text-overflow: ellipsis;
    }

    </style>
    """,
    unsafe_allow_html=True
)

# ----------------------------
# DATASET
# ----------------------------
data = [
    {
        "name": "Ultramarines",
        "type": "Loyalist",
        "primarch": "Roboute Guilliman",
        "sub": "Novamarines, Silver Templars, Genesis Chapter",
        "url": "https://warhammer40k.fandom.com/wiki/Ultramarines"
    },
    {
        "name": "Dark Angels",
        "type": "Loyalist",
        "primarch": "Lion El'Jonson",
        "sub": "Deathwing, Ravenwing, Unforgiven",
        "url": "https://warhammer40k.fandom.com/wiki/Dark_Angels"
    },
    {
        "name": "Space Wolves",
        "type": "Loyalist",
        "primarch": "Leman Russ",
        "sub": "Great Companies, Grey Hunters, Long Fangs",
        "url": "https://warhammer40k.fandom.com/wiki/Space_Wolves"
    },
    {
        "name": "Blood Angels",
        "type": "Loyalist",
        "primarch": "Sanguinius",
        "sub": "Flesh Tearers, Lamenters, Blood Drinkers",
        "url": "https://warhammer40k.fandom.com/wiki/Blood_Angels"
    },
    {
        "name": "Imperial Fists",
        "type": "Loyalist",
        "primarch": "Rogal Dorn",
        "sub": "Black Templars, Crimson Fists",
        "url": "https://warhammer40k.fandom.com/wiki/Imperial_Fists"
    },
    {
        "name": "Black Legion",
        "type": "Chaos",
        "primarch": "Horus / Abaddon",
        "sub": "Ezekarion, Justaerin",
        "url": "https://warhammer40k.fandom.com/wiki/Black_Legion"
    },
    {
        "name": "World Eaters",
        "type": "Chaos",
        "primarch": "Angron",
        "sub": "Khorne Berzerkers, Red Butchers",
        "url": "https://warhammer40k.fandom.com/wiki/World_Eaters"
    },
    {
        "name": "Death Guard",
        "type": "Chaos",
        "primarch": "Mortarion",
        "sub": "Plague Marines, Blightlords",
        "url": "https://warhammer40k.fandom.com/wiki/Death_Guard"
    },
]
# ----------------------------
# FULL DATASET (LEGIONS)
# ----------------------------
data = [
    # ===== LOYALIST =====
    {
        "name": "Ultramarines",
        "type": "Loyalist",
        "primarch": "Roboute Guilliman",
        "sub": "Novamarines, Silver Templars, Genesis Chapter, Excel Sheet Guy, Basic",
        "url": "https://warhammer40k.fandom.com/wiki/Ultramarines"
    },
    {
        "name": "Dark Angels",
        "type": "Loyalist",
        "primarch": "Lion El'Jonson",
        "sub": "Deathwing, Ravenwing, Unforgiven",
        "url": "https://warhammer40k.fandom.com/wiki/Dark_Angels"
    },
    {
        "name": "Space Wolves",
        "type": "Loyalist",
        "primarch": "Leman Russ",
        "sub": "Great Companies, Grey Hunters, Long Fangs",
        "url": "https://warhammer40k.fandom.com/wiki/Space_Wolves"
    },
    {
        "name": "Blood Angels",
        "type": "Loyalist",
        "primarch": "Sanguinius",
        "sub": "Flesh Tearers, Lamenters, Blood Drinkers, Gay, Doing Art",
        "url": "https://warhammer40k.fandom.com/wiki/Blood_Angels"
    },
    {
        "name": "Imperial Fists",
        "type": "Loyalist",
        "primarch": "Rogal Dorn",
        "sub": "Black Templars, Crimson Fists, 40K Daddy",
        "url": "https://warhammer40k.fandom.com/wiki/Imperial_Fists"
    },
    {
        "name": "White Scars",
        "type": "Loyalist",
        "primarch": "Jaghatai Khan",
        "sub": "Mantis Warriors, Storm Lords, Vanessa's pick",
        "url": "https://warhammer40k.fandom.com/wiki/White_Scars"
    },
    {
        "name": "Iron Hands",
        "type": "Loyalist",
        "primarch": "Ferrus Manus",
        "sub": "Sons of Medusa, Red Talons",
        "url": "https://warhammer40k.fandom.com/wiki/Iron_Hands"
    },
    {
        "name": "Raven Guard",
        "type": "Loyalist",
        "primarch": "Corvus Corax",
        "sub": "Raptors, Black Guard, Team Uniform",
        "url": "https://warhammer40k.fandom.com/wiki/Raven_Guard"
    },
    {
        "name": "Salamanders",
        "type": "Loyalist",
        "primarch": "Vulkan",
        "sub": "No major successors (rare lineage), Mercy Guy",
        "url": "https://warhammer40k.fandom.com/wiki/Salamanders"
    },

    # ===== TRAITOR =====
    {
        "name": "Black Legion",
        "type": "Traitor",
        "primarch": "Horus / Abaddon",
        "sub": "Ezekarion, Justaerin",
        "url": "https://warhammer40k.fandom.com/wiki/Black_Legion"
    },
    {
        "name": "World Eaters",
        "type": "Traitor",
        "primarch": "Angron",
        "sub": "Khorne Berzerkers, Red Butchers",
        "url": "https://warhammer40k.fandom.com/wiki/World_Eaters"
    },
    {
        "name": "Thousand Sons",
        "type": "Traitor",
        "primarch": "Magnus the Red",
        "sub": "Rubric Marines, Scarab Occult, Best Color Award",
        "url": "https://warhammer40k.fandom.com/wiki/Thousand_Sons"
    },
    {
        "name": "Death Guard",
        "type": "Traitor",
        "primarch": "Mortarion",
        "sub": "Plague Marines, Blightlords",
        "url": "https://warhammer40k.fandom.com/wiki/Death_Guard"
    },
    {
        "name": "Emperor's Children",
        "type": "Traitor",
        "primarch": "Fulgrim",
        "sub": "Noise Marines, Kakophoni, PINK",
        "url": "https://warhammer40k.fandom.com/wiki/Emperor%27s_Children"
    },
    {
        "name": "Night Lords",
        "type": "Traitor",
        "primarch": "Konrad Curze",
        "sub": "Terror Squads, Talons of the Night",
        "url": "https://warhammer40k.fandom.com/wiki/Night_Lords"
    },
    {
        "name": "Word Bearers",
        "type": "Traitor",
        "primarch": "Lorgar",
        "sub": "Dark Apostles, Gal Vorbak",
        "url": "https://warhammer40k.fandom.com/wiki/Word_Bearers"
    },
    {
        "name": "Iron Warriors",
        "type": "Traitor",
        "primarch": "Perturabo",
        "sub": "Warsmiths, Siege Tyrants",
        "url": "https://warhammer40k.fandom.com/wiki/Iron_Warriors"
    },
    {
        "name": "Alpha Legion",
        "type": "Traitor",
        "primarch": "Alpharius / Omegon",
        "sub": "Hydra Cells, Sleeper Agents",
        "url": "https://warhammer40k.fandom.com/wiki/Alpha_Legion"
    },
]

# ----------------------------
# STATE
# ----------------------------
if "faction_filter" not in st.session_state:
    st.session_state.faction_filter = "All"

if "search" not in st.session_state:
    st.session_state.search = ""

# ----------------------------
# BUTTONS
# ----------------------------
st.markdown("### 🏷️ Quick Tags")

col1, col2, col3 = st.columns(3)

if col1.button("☠️ Traitor"):
    st.session_state.faction_filter = "Traitor"
    st.session_state.search = ""

if col2.button("🛡️ Loyalist"):
    st.session_state.faction_filter = "Loyalist"
    st.session_state.search = ""

# ----------------------------
# SEARCH
# ----------------------------
name = st.text_input("Search Legion or Faction", key="search_input")
st.session_state.search = name

query = (st.session_state.search or "").lower()

# ----------------------------
# BASE DATA
# ----------------------------
matches = data

# ----------------------------
# FILTER 1: FACTION
# ----------------------------
if st.session_state.faction_filter != "All":
    matches = [m for m in matches if m["type"] == st.session_state.faction_filter]

# ----------------------------
# FILTER 2: SEARCH
# ----------------------------
if query:
    def score(item):
        return max(
            fuzz.partial_ratio(query, item["name"].lower()),
            fuzz.partial_ratio(query, item["primarch"].lower()),
            fuzz.partial_ratio(query, item["sub"].lower()),
            fuzz.partial_ratio(query, item["type"].lower())
        )

    matches = sorted(matches, key=score, reverse=True)
    matches = [m for m in matches if score(m) > 40]

# ----------------------------
# DISPLAY
# ----------------------------
if matches:

    st.subheader("📜 Codex Entries")

    for item in matches:

        with st.expander(item["name"]):

            col1, col2 = st.columns(2)

            with col1:
                st.markdown(f"**⚔️ Type:** {item['type']}")
                st.markdown(f"**👑 Primarch:** {item['primarch']}")

            with col2:
                st.markdown("**🧬 Sub-factions:**")
                st.write(item["sub"])

else:
    st.warning("No records found in the Codex")